import { Crud } from "./Crud";
import "./globals.css";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bobae's App",
  description: "Generated by BobaeJ",
};

export default async function RootLayout({ children }) {
  // const [topics, setTopics] = useState([]);
  // useEffect(() => {
  //   fetch("http://localhost:9999/topics")
  //     .then((resp) => resp.json())
  //     .then((result) => setTopics(result));
  // }, []);
  const resp = await fetch("http://localhost:9999/topics", {
    next: { revalidate: 0 },
  });
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">Main_WEB(globalLayout)</Link>
          {/* {topics} */}
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <h3>
                  <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                </h3>
              </li>
            );
          })}
        </ol>

        <h3>page-children</h3>
        <div id="children">{children}</div>
        <Crud />
      </body>
    </html>
  );
}
// json-server --watch db.json --port 9999
// , {
//   next: { cache: "no-store" },
// }
